version: '3.8'

services:
  app:
    build: .
    environment:
      -MONGO_URL: 'mongodb://db:27017/gamesaver'
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - /data/db
